_target_: transformers.AutoModelForCausalLM.from_pretrained
pretrained_model_name_or_path: "shisa-ai/shisa-jamba-v1-checkpoint-2416"
trust_remote_code: true
device_map: "auto"
load_in_8bit: false
load_in_4bit: false
