base_model: Qwen/Qwen2.5-32B-Instruct
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

# https://axolotl-ai-cloud.github.io/axolotl/docs/dataset-formats/conversation.html#chat_template
chat_template: qwen_25
datasets:
  - path: augmxnt/ultra-orca-boros-en-ja-v1
    type: chat_template

    field_messages: conversations
    message_field_role: from
    message_field_content: value

dataset_prepared_path: last_run_prepared
val_set_size: 0.05
output_dir: ./outputs/shisa-v1-qwen2.5-32b

sequence_len: 8192
sample_packing: true
pad_to_sequence_len: true

use_wandb: true
wandb_project: shisa-v2
wandb_entity: augmxnt
wandb_name: mi300x-shisa-v1-qwen2.5-32b

gradient_accumulation_steps: 2
micro_batch_size: 4
num_epochs: 3
optimizer: paged_adamw_8bit
lr_scheduler: linear
learning_rate: 8e-6

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
early_stopping_patience:
resume_from_checkpoint:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 100
evals_per_epoch: 2
eval_table_size:
saves_per_epoch: 1
debug:
deepspeed: axolotl/deepspeed_configs/zero3_bf16.json
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
