base_model: meta-llama/Llama-3.1-70B-Instruct
model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

# doesn't work...
# hub_model_id: shisa-ai/shisa-llama3-70b-v1
# hub_strategy: end

use_wandb: true
wandb_project: shisa-v2
wandb_entity: augmxnt
wandb_name: mi300x-shisa-v1-llama3.1-70b-liger.2

chat_template: llama3

datasets:
  - path: augmxnt/ultra-orca-boros-en-ja-v1
    type: chat_template

    field_messages: conversations
    message_field_role: from
    message_field_content: value

dataset_prepared_path: last_run_prepared
val_set_size: 0.05
output_dir: ./outputs/shisa-v1-llama3.1-70b

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

neftune_noise_alpha: 5

gradient_accumulation_steps: 1
micro_batch_size: 8
num_epochs: 3
optimizer: paged_adamw_8bit
lr_scheduler: linear
learning_rate: 8e-6

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32:

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
early_stopping_patience:
resume_from_checkpoint:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_ratio: 0.1
evals_per_epoch: 2
eval_table_size:
saves_per_epoch: 0
debug:
deepspeed: axolotl/deepspeed_configs/zero3_bf16.json
weight_decay: 0.05
fsdp:
fsdp_config:
special_tokens:
  pad_token: <|end_of_text|>

plugins:
  - axolotl.integrations.liger.LigerPlugin
liger_rope: true
liger_rms_norm: true
liger_swiglu: true
liger_fused_linear_cross_entropy: true
