base_model: tokyotech-llm/Swallow-MX-8x7b-NVE-v0.1
model_type: AutoModelForCausalLM
tokenizer_type: LlamaTokenizer
trust_remote_code: true

load_in_8bit: false
load_in_4bit: false
strict: false

chat_template: inst
datasets:
  - path: augmxnt/ultra-orca-boros-en-ja-v1
    type: sharegpt
dataset_prepared_path: last_run_prepared
val_set_size: 0.05
output_dir: ./outputs/basemodel-swallowmx-8x22b-fsdp

model_config:
  output_router_logits: true

sequence_len: 2048
sample_packing: true
pad_to_sequence_len: true

use_wandb: true8192
wandb_project: shisa-v2
wandb_entity: augmxnt
wandb_name: shisa-swallowmx-13a47b-v1.fsdp

global_batch_size: 4
gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 3
# https://github.com/huggingface/transformers/issues/22101
# https://github.com/huggingface/transformers/blob/main/src/transformers/training_args.py#L141
optimizer: adamw_torch_fused
lr_scheduler: linear
learning_rate: 2e-5

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: true

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_ratio: 0.1
evals_per_epoch: 2
eval_table_size:
saves_per_epoch: 1
debug:
deepspeed: 
weight_decay: 0.0
fsdp:
  - full_shard
  - auto_wrap
fsdp_config:
  fsdp_limit_all_gathers: true
  fsdp_sync_module_states: true
  fsdp_offload_params: true
  fsdp_use_orig_params: true
  fsdp_backward_prefetch_policy: BACKWARD_PRE
  fsdp_forward_prefetch: true
  fsdp_cpu_ram_efficient_loading: true
  fsdp_transformer_layer_cls_to_wrap: MixtralDecoderLayer
  fsdp_state_dict_type: SHARDED_STATE_DICT
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
special_tokens:
