# train w/ shisa-ai/shisa-v1-athenev2-reannotated-filtered

base_model: Qwen/Qwen3-30B-A3B
model_config:
  output_router_logits: true
  router_aux_loss_coef: 0.001

load_in_8bit: false
load_in_4bit: false
strict: false

# User Liger
plugins:
  - axolotl.integrations.liger.LigerPlugin
liger_rope: true
liger_rms_norm: true
liger_glu_activation: true
liger_fused_linear_cross_entropy: true

chat_template: tokenizer_default
datasets:
  - path: shisa-ai/shisa-v2-2025-6-17-sharegpt
    type: chat_template
    field_messages: conversations
    message_property_mappings:
      role: from
      content: value
    roles:
      system:
        - system
      assistant:
        - gpt
        - model
        - assistant
      user:
        - human
        - user
  - path: shisa-ai/shisa-v2-roleplaying-sft
    type: chat_template
    field_messages: conversations
    message_property_mappings:
      role: role
      content: content
    roles:
      system:
        - system
      assistant:
        - gpt
        - model
        - assistant
      user:
        - human
        - user
    roles_to_train: ["assistant"]
  - path: shisa-ai/translation_set_april_6
    split: train[:25%]
    type: chat_template
    field_messages: conversations
    message_property_mappings:
      role: role
      content: content
    roles:
      system:
        - system
      assistant:
        - gpt
        - model
        - assistant
      user:
        - human
        - user
    roles_to_train: ["assistant"]
  - path: shisa-ai/rewild-set-deepseek-subset
    split: train[:25%]
    type: chat_template
    field_messages: conversations
    message_property_mappings:
      role: role
      content: content
    roles:
      system:
        - system
      assistant:
        - gpt
        - model
        - assistant
      user:
        - human
        - user
    roles_to_train: ["assistant"]
  - path: shisa-ai/magpie-ultra-set
    split: train[:8%]
    type: chat_template
    field_messages: conversations
    message_property_mappings:
      role: role
      content: content
    roles:
      system:
        - system
      assistant:
        - gpt
        - model
        - assistant
      user:
        - human
        - user
    roles_to_train: ["assistant"]
  - path: shisa-ai/magpie-advanced-questions-set
    split: train[:8%]
    type: chat_template
    field_messages: conversations
    message_property_mappings:
      role: role
      content: content
    roles:
      system:
        - system
      assistant:
        - gpt
        - model
        - assistant
      user:
        - human
        - user
    roles_to_train: ["assistant"]
  - path: shisa-ai/japan-magpie-set
    split: train
    type: chat_template
    field_messages: conversations
    message_property_mappings:
      role: role
      content: content
    roles:
      system:
        - system
      assistant:
        - gpt
        - model
        - assistant
      user:
        - human
        - user
    roles_to_train: ["assistant"]
  - path: shisa-ai/shisa-v2-instruction-following-sft
    split: train[:50%]
    type: chat_template
    field_messages: conversations
    message_property_mappings:
      role: role
      content: content
    roles:
      system:
        - system
      assistant:
        - gpt
        - model
        - assistant
      user:
        - human
        - user
    roles_to_train: ["assistant"]
    
dataset_prepared_path: last_run_prepared
val_set_size: 0
output_dir: /data/outputs/shisa-v2-qwen3-30b-a3b

sequence_len: 8192
sample_packing: true
flash_attention: true
pad_to_sequence_len: true

# Must match quantization for QAT
# qat:
#   activation_dtype: int8
#   weight_dtype: int4
#   group_size: 256
#   fake_quant_after_n_steps: 1000

# marginal difference
neftune_noise_alpha: 5

use_wandb: true
wandb_project: shisa-v2.1
wandb_entity: augmxnt
wandb_name: qwen3-v2

# This LR is for 4 nodes * 8 GPU * 4 mbs = 128 gbs
#                1 node * 4 GPU * 8 mbs * 4ga = 128 gbs
#                1 node * 8 GPU * 16 mbs * 1gas = 128 gbs
gradient_accumulation_steps: 1
micro_batch_size: 16
num_epochs: 3
optimizer: paged_adamw_8bit
# optimizer: muon
# optimizer: adamw_torch_4bit
lr_scheduler: linear
learning_rate: 1.63e-05

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
early_stopping_patience:
resume_from_checkpoint:
logging_steps: 1

warmup_steps: 100
evals_per_epoch: 0
eval_table_size:
saves_per_epoch: 1
save_total_limit: 3 # Only store a single checkpoint
debug:
deepspeed: zero2_moe.json
weight_decay: 1e-4
fsdp:
fsdp_config:
special_tokens:
