# Axolotl SFT configuration for Qwen3 30B-A3B on 8x MI300X
# mbs=16 20h x 8 GPU = 160h - 13/1188 - using about 124GB VRAM (65GB for model loading vs 12GB)
base_model: Qwen/Qwen3-30B-A3B-Instruct-2507

load_in_8bit: false
load_in_4bit: false
strict: false

plugins:
  - axolotl.integrations.liger.LigerPlugin
  - axolotl.integrations.densemixer.DenseMixerPlugin
liger_rope: true
liger_rms_norm: true
liger_glu_activation: true
liger_fused_linear_cross_entropy: true

chat_template: tokenizer_default
datasets:
  - path: ./sft.shisa-v2.1.jsonl
    type: chat_template
    field_messages: conversations
    message_property_mappings:
      role: role
      content: content
    roles:
      system:
        - system
      assistant:
        - assistant
        - gpt
        - model
      user:
        - user
        - human
    roles_to_train: ["assistant"]

dataset_prepared_path: cached_formatted_dataset/094-qwen3-30b-a3b-v2.1-sft
val_set_size: 0
output_dir: /data/outputs/095-qwen3-30b-a3b-v2.1-sft

sequence_len: 8192
sample_packing: true
flash_attention: true
pad_to_sequence_len: true

neftune_noise_alpha: 5

use_wandb: true
wandb_entity: augmxnt
wandb_project: shisa-v2.1
wandb_name: 095-qwen3-30b-a3b-v2.1-sft

gradient_accumulation_steps: 1
micro_batch_size: 16
num_epochs: 3
optimizer: adamw_torch_8bit
lr_scheduler: linear
learning_rate: 1.63e-05

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
logging_steps: 1

warmup_ratio: 0.03
saves_per_epoch: 1
save_total_limit: 3

deepspeed: zero2_moe_offload.json
weight_decay: 1e-4
fsdp:
fsdp_config:
special_tokens:
