# Axolotl SFT configuration for Qwen3-8B on 8x MI300X
# 2X LR

base_model: meta-llama/Llama-3.3-70B-Instruct

load_in_8bit: false
load_in_4bit: false
strict: false

plugins:
  - axolotl.integrations.liger.LigerPlugin
liger_rope: true
liger_rms_norm: true
liger_glu_activation: true
liger_fused_linear_cross_entropy: true

chat_template: tokenizer_default
chat_template_kwargs:
  enable_thinking: false
datasets:
  - path: sft.shisa-v2.1.jsonl
    type: chat_template
    field_messages: conversations
    message_property_mappings:
      role: role
      content: content
    roles:
      system:
        - system
      assistant:
        - assistant
        - gpt
        - model
      user:
        - user
        - human
    roles_to_train: ["assistant"]

dataset_prepared_path: data/168
val_set_size: 0
output_dir: /data/outputs/168-llama3.3-70b-v2.1-sft-6.6e6

sequence_len: 8192
sample_packing: true
flash_attention: true
pad_to_sequence_len: true

neftune_noise_alpha: 5

use_wandb: true
wandb_entity: augmxnt
wandb_project: shisa-v2.1
wandb_name: 168-llama3.3-70b-v2.1-sft-6.6e6

# GBS 128 = 8 GPU x 16 MBS x 1 GAS
gradient_accumulation_steps: 4
micro_batch_size: 4
num_epochs: 3
optimizer: adamw_torch_8bit
lr_scheduler: cosine
learning_rate: 6.6e-06

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
logging_steps: 1

warmup_ratio: 0.03
saves_per_epoch: 1
save_total_limit: 3

deepspeed: zero3_bf16.json
weight_decay: 1e-4
fsdp:
fsdp_config:
special_tokens:
